{% set name = "Chameleon" %}
{% set version = "4.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 910cd729f6f7f38adad132ee51faa4f3ccc8344a6721aac31aa51a31f5781c1b

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<39]

requirements:
  host:
    - pip
    - python
    - setuptools >=42
    - wheel
  run:
    - python
    - importlib-metadata # [py<310]

test:
  imports:
    - chameleon
    - chameleon.tests
    - chameleon.utils
    - chameleon.zpt
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest --pyargs chameleon.tests
  requires:
    - pip
    - pytest

about:
  home: https://chameleon.readthedocs.org
  # Zope Public License (ZPL) Version 2.1
  # This license has been certified as open source. It has also
  # been designated as GPL compatible by the Free Software
  # Foundation (FSF).
  # https://repoze.org/license.html
  license: ZPL
  license_family: Other
  license_file: LICENSE.txt
  summary: HTML/XML template engine for Python
  description: |
    Chameleon is an HTML/XML template engine for Python designed to generate
    the document output of a web application, typically HTML markup or XML.
  doc_url: https://chameleon.readthedocs.org
  dev_url: https://github.com/malthe/chameleon

extra:
  recipe-maintainers:
    - nehaljwani
  skip-lints:
    - incorrect_license
